name: React-GH-actions
on:
  [push]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkcout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: cd frontend
      - run: npm ci
      - run: npm run build --if-present
